### ISSUE TITLE
Do you have any ideas about opencore 0.6.1 ？

### ISSUE THREAD

**Issue by liuzhe1947** [asle/lenovo_m93p_mini_hackintosh#1]
Hello, I am your github fan. Thank you for sharing EFI and using EFI files. The EFI you shared is basically perfect, but I have two problems.
1. Use Magic Keyboard @ and "On the contrary, some keys have the same problem.
2. The latest 10.15.7 has been released, can I update OC0.6.1?
Thank you~~~

**Comment by asle** [comment]
Hi, thanks for your kind words!
1) Can you map the keys in preferences -> keyboard (or Language International) ?
2) I have 3 different versions of m93p, It seems they all support Turbo Boost:
https://www.cpubenchmark.net/compare/Intel-i5-4570T-vs-Intel-i5-4590T-vs-Intel-i7-4785T/2041vs2276vs2260

3) I had no problem updating to 10.15.7 on OC 0.6.1

I also purchased a i7-4785T and upgraded one of the i5 cpus. Works great and almost doubles the speed. Let me know if you have any questions and I will try to help.

cheers,

~asle

**Comment by liuzhe1947** [comment]
> 嗨，谢谢您的客气！1）您可以在首选项->键盘（或语言国际）中映射键吗？2）我有3个不同的m93p版本，似乎它们都支持Turbo Boost：[https](https://www.cpubenchmark.net/compare/Intel-i5-4570T-vs-Intel-i5-4590T-vs-Intel-i7-4785T/2041vs2276vs2260) ://www.cpubenchmark.net/compare/Intel-i5-4570T-vs-Intel-i5-4590T-vs-Intel-i7- [4785T / 2041vs2276vs2260](https://www.cpubenchmark.net/compare/Intel-i5-4570T-vs-Intel-i5-4590T-vs-Intel-i7-4785T/2041vs2276vs2260) 3）我在OC 0.6.1上更新到10.15.7没问题，我还购买了i7-4785T并升级了i5 cpus之一。效果很好，速度几乎提高了一倍。如果您有任何问题，请告诉我，我们将尽力提供帮助。干杯，〜asle
> […](#)
> 2020年10月1日14:52 +0200，liuzhe1947 ***@***.***>写道：您好，我是您github粉丝的粉丝。感谢您共享EFI和使用EFI文件。总体来说感觉不错，但是我有三个问题。1.使用魔术键盘@和“相反，并且某些键具有相同的问题。2.此CPU是否支持Turbo Boost？EFI是否已支持它？3.最新的10.15.7已发布，我可以吗？更新OC0.6.1，谢谢~~~ —之所以收到此邮件，是因为您已订阅此线程，请直接回复此电子邮件，在GitHub上查看或取消订阅。



> 嗨，谢谢您的客气！1）您可以在首选项->键盘（或语言国际）中映射键吗？2）我有3个不同的m93p版本，似乎它们都支持Turbo Boost：[https](https://www.cpubenchmark.net/compare/Intel-i5-4570T-vs-Intel-i5-4590T-vs-Intel-i7-4785T/2041vs2276vs2260) ://www.cpubenchmark.net/compare/Intel-i5-4570T-vs-Intel-i5-4590T-vs-Intel-i7- [4785T / 2041vs2276vs2260](https://www.cpubenchmark.net/compare/Intel-i5-4570T-vs-Intel-i5-4590T-vs-Intel-i7-4785T/2041vs2276vs2260) 3）我在OC 0.6.1上更新到10.15.7没问题，我还购买了i7-4785T并升级了i5 cpus之一。效果很好，速度几乎提高了一倍。如果您有任何问题，请告诉我，我们将尽力提供帮助。干杯，〜asle
> […](#)
> 2020年10月1日14:52 +0200，liuzhe1947 ***@***.***>写道：您好，我是您github粉丝的粉丝。感谢您共享EFI和使用EFI文件。总体来说感觉不错，但是我有三个问题。1.使用魔术键盘@和“相反，并且某些键具有相同的问题。2.此CPU是否支持Turbo Boost？EFI是否已支持它？3.最新的10.15.7已发布，我可以吗？更新OC0.6.1，谢谢~~~ —之所以收到此邮件，是因为您已订阅此线程，请直接回复此电子邮件，在GitHub上查看或取消订阅。
Hi asle, thanks for your reply.
1) I use the wonderful control keyboard 2 Chinese (phonetic version) purchase address: https: //www.apple.com.cn/shop/product/MQ052CH/A fnode = fa171a3912ba0e42b5d2e0820578d3c2ece6f3a5121edf7c7b48a5c204d635cbfc058a99c61ea6f88a8c907c590d3503081739ab42190d4a1ce7bb700c2ebbf7b18ee6854f55b0cca8c980a119327a6e854b8a6b6e6c99d737715b84851c291854bae99ff838acd3eb636f3685e4b95e?
Because this keyboard is a Bluetooth connection, you can change the keyboard type in Preferences -> Keyboard -> No, so the keyboard type cannot be modified or mapped.
2). Can you share your 0.61 version of the EFI file, it will be a very good thing.
thanks for your help .

**Comment by asle** [comment]
I am soon updating the repo for OpenCore 0.6.2 which seems to work fine.
