### ISSUE TITLE
Problem with OpenCore installation on Disk EFI Partition

### ISSUE THREAD

**Issue by Morzilla** [asle/lenovo_m93p_mini_hackintosh#11]
Hello! I have a problem with my M93p Tiny Hackintosh (i5-4590T, 8GB RAM, SSD Lexar 256GB SATA3):
I installed Big Sur (10.15.2) with the OpenCore version on this repository on a 4GB USB pendrive flawlessy (simply copying the EFI folder on the root of the pendrive without any modifications, except serials, MB, UUID, etc.).
When I try to copy the entire EFI folder on the EFI partition on SATA SSD Disk (mounted with diskutil mount disk0s1), OpenCore start normally, I can select the Big Sur entry, but at this point the PC keeps rebooting after 5 seconds without apparently any error (as far as I can see, only "regular" messages).
I can boot Big Sur without any problems if at the POST I select as boot device the pendrive with the same opencore installation.
Any clue? Thanks!

**Comment by asle** [comment]
It seems obvious that something is wrong with your drive or one of the partitions. I understand if you boot from the USB stick you can then start Big Sur on your main drive. So I suggest reformatting the EFI partition. Here is a very good guide:
https://apple.stackexchange.com/questions/57597/how-to-fix-broken-efi-partition/58892#58892

**Comment by Morzilla** [comment]
Hello asle, thanks for your reply. I just found the problem!
The EFI partition was OK, it was the boot mode option in BIOS set in "Auto" and not in "UEFI Only"... I don't know why, but opencore was able to boot even in "legacy" mode instead of give me a boot error.. now I can use OpenCore on my local EFI partition! Thanks!

**Comment by asle** [comment]
> Hello asle, thanks for your reply. I just found the problem!
> The EFI partition was OK, it was the boot mode option in BIOS set in "Auto" and not in "UEFI Only"... I don't know why, but opencore was able to boot even in "legacy" mode instead of give me a boot error.. now I can use OpenCore on my local EFI partition! Thanks!

Ah I should have thought about that but like you wrote, the "Auto" value seems to work on USB but gets confused with the internal drives EFI.
