### ISSUE TITLE
AW-CE123H BCM94352HMB Compatibility

### ISSUE THREAD

**Issue by Tokobotenkai** [asle/lenovo_m93p_mini_hackintosh#17]
Hi,

I am not sure if this is the right place to contact you.

I was wondering can I just grab any AW-CE123H off eBay or Aliexpress? I heard supposedly there's firmware for it?

For the M93p do I need to update the whitelist for the computer to recognise it?

Thank you.

**Comment by asle** [comment]
Thank you for your input. Would you be able to provide your config.plist or let me know what changes you did compared to my config? Then I will update til repo for Montery. Also how fast is your CPU compared to the standard i5 4570T/4590T and i7 4765T/4785T. Would like to see some numbers from Geekbench and NovaBench.

**Comment by Tokobotenkai** [comment]
I actually changed and changed until I am not sure what I changed overall. I could share my EFI but I remember I have to omit certain info right?

Here are my Geekbench results:
https://browser.geekbench.com/v6/cpu/4447706
https://browser.geekbench.com/v6/compute/1610924

I tried to run Metal but there was a system panic and it froze the system.

These are the Novabench results
![Screenshot 2024-01-19 at 3 37 39 AM](https://github.com/asle/lenovo_m93p_mini_hackintosh/assets/83901992/4157c5a8-8dff-4d2d-8911-60dc4a32064f)
![Screenshot 2024-01-19 at 3 38 19 AM](https://github.com/asle/lenovo_m93p_mini_hackintosh/assets/83901992/a50708cb-9d78-4d23-aabb-119e34b6c6ea)
