### ISSUE TITLE
Audio is not working from front panel

### ISSUE THREAD

**Issue by angeloruggieridj** [asle/lenovo_m93p_mini_hackintosh#2]
With this configuration, I don't have any audio signal from front panel and, for HDMI audio, macOS doesn't give me the possibility to increase or decrease the volume.

No sound when an iMessage vocal is played.

**Comment by asle** [comment]
Keyboard volume control does not work with HDMI audio for any Mac so this has nothing to do with hackintosh!

Send me your config.plist and I can check if audio is set up correctly.

~asle

**Comment by asle** [comment]
I have replaced VodooHDA with AppleALC and the correct input/output shows now. Still no internal speaker. Will update the repo soon.

**Comment by asle** [comment]
Just a note that when I use AppleALC and alcid=33 I get 2 outputs:
- Internal speaker
- HDMI audio
- NO headphone output!
Input:
- Microphone
- Line input
