### ISSUE TITLE
Issues with sound and screen

### ISSUE THREAD

**Issue by pedrohqb** [asle/lenovo_m93p_mini_hackintosh#3]
Hello. I am having some issues:

1) I don't have any internal speaker sound. Is that an issue also for you?

2): When I boot, I get the login screen normally; but after about 5 seconds, I get a black screen, and in 2 seconds, the screen comes back. I have no further problems. I am using HDMI cable with a display port adaptor.

Another thing that seemed at first to be an issue, but it is not: on Sound properties, there seems to have two sound input (microphone), but m93p mini does only have one, on the front. I checked my Arch Linux sound properties, and it also does recognize two sound inputs (microphone). It seems to be a hardware thing.

**Comment by asle** [comment]
Hi,
I had to test this. I do not have internal sound. Still struggling with that. I suggest you replace the VoodooHDA.kext with AppleALC.kext. Then I get correct inputs and outputs. I tested also HDMI sound with works fine then. I am still testing different alcid numbers to see if I can get the internal speaker to show up in sound preferences. I tested 1 and 11 and get the same input/output. But still no internal speaker. I will update GitHub as soon as I have time.

~asle

**Comment by asle** [comment]
I have replaced VoodooHDA.kext with AppleALC.kext. In sound I can now see 
Input: **Line input**
Output : **Headphones**, **HDMI** (I have a DP to HDMI adapter, and **Airplay** (my AppleTV).
This corresponds to the correct input/output devices. Missing is INTERNAL. Has anyone seen the internal output in any config?

Sound is working out on HDMI and headphones. Sound in is **NOT** working even if I choose **line input**.
In **Hackintool** I see 2 sound devices and this is confusing. Seems related to your Linux properties.

8 Series/C220 Series Chipset High Definition Audio Controller    PciRoot(0x0)/Pci(0x1B,0x0)
Xeon E3-1200 v/3/4th Gen Core Processor HD Audio Controller  PciRoot(0x0)/Pci(0x3,0x0)

In config.plist under DeviceProperties I have added the first controller. The m93p uses audio controller Realtek ALC283 and support layouts are according to https://github.com/acidanthera/AppleALC/wiki/Supported-codecs
layout 1, 3, 11, 15, 44, 66

I have only success with 11.  In Hackintool->Sound I see Realtek ALC283 and Intel Haswell HDMI both registered to Sub Device (0c30A3). Not sure what this means related to the device ID.

**Comment by pedrohqb** [comment]
Thank for your inputs. Following your example, I tried to several layouts and I found out that layout 15 works very well. As in Windows and Linux, if you remove your headphone cable, the internal speaker will start work. Sadly, there are two disadvantages: the mic does not work anymore and I have no HDMI sound. It seems that the layout 15 was made for LENOVO IDEAPAD 14 ( https://github.com/acidanthera/AppleALC/commit/4975e221092e74dd40d664c639d69c04c88e6f61?short_path=c275fec#diff-9b8fab691c00b9e5380b19ce882f3271 ). It seems it may be patched to work with m93p.

At the moment, I will have stick with VoodooHDA.

**Comment by pedrohqb** [comment]
Asle, hello. I am having problems with HDMI because my HDMI controller seems to be unsupported, since its device id is 0c0c: 

Slot:   0000:00:03.0
Class:  Audio device [0403]
Vendor: Intel Corporation [8086]
Device: Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller [0c0c]
SVendor:        Lenovo [17aa]
SDevice:        Device [30a3]
Rev:    06

Source: https://github.com/RehabMan/OS-X-Fake-PCI-ID

Would you be kind to send me your device id? Yours seems to work. You may find it running "$ lspci -vmmnnD" on Linux.

Now I will have to figure out how to fake my HDMI controllers id.

**Comment by asle** [comment]
> Thank for your inputs. Following your example, I tried to several layouts and I found out that layout 15 works very well. As in Windows and Linux, if you remove your headphone cable, the internal speaker will start work. Sadly, there are two disadvantages: the mic does not work anymore and I have no HDMI sound. It seems that the layout 15 was made for LENOVO IDEAPAD 14 ( [acidanthera/AppleALC@4975e22?short_path=c275fec#diff-9b8fab691c00b9e5380b19ce882f3271](https://github.com/acidanthera/AppleALC/commit/4975e221092e74dd40d664c639d69c04c88e6f61?short_path=c275fec#diff-9b8fab691c00b9e5380b19ce882f3271) ). It seems it may be patched to work with m93p.
> 
> At the moment, I will have stick with VoodooHDA.

I still do not see the internal speaker if I change to alcid=15. I get the same result if I use 1 or 11.

**Comment by asle** [comment]
> Asle, hello. I am having problems with HDMI because my HDMI controller seems to be unsupported, since its device id is 0c0c:
> 
> Slot: 0000:00:03.0
> Class: Audio device [0403]
> Vendor: Intel Corporation [8086]
> Device: Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller [0c0c]
> SVendor: Lenovo [17aa]
> SDevice: Device [30a3]
> Rev: 06
> 
> Source: https://github.com/RehabMan/OS-X-Fake-PCI-ID
> 
> Would you be kind to send me your device id? Yours seems to work. You may find it running "$ lspci -vmmnnD" on Linux.
> 
> Now I will have to figure out how to fake my HDMI controllers id.

I am not sure what you mean but here is my HDMI audio. Is this what you want? I do not have Linux at the moment.
Class:		AppleHDAHDMI_DPDriver
Vendor:		Intel Corporation (0x8086)
Device:		Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller (0x0C0C)*
Sub Vendor:	Lenovo (0x17AA)
Sub Device: 	??? (0x30A3)

**Comment by pedrohqb** [comment]
I managed to fake the PCI ID and it did not work. Yours is exactly as mine. That's very weird.

**Comment by pedrohqb** [comment]
I managed to make the internal sound work, using layout 11, by adding these to config.plist: https://www.reddit.com/r/hackintosh/comments/j9gz6b/m93p_tiny_hackintosh_problems_with_audio_and_mic/g8loq5g/?utm_source=reddit&utm_medium=web2x&context=3

See if that works for you.

**Comment by asle** [comment]
I added the 2 patches from your Reddit post. I still do not get any internal sound. HDMI still working as before. I changed alcid back to 11. Can not see any change from alcid=1 or 15. Also I can see "line input" as in device but I can not get sound in on that input. I noticed I have the level bars moving when I connected a mp3 player to line input but still no sound in e.g. Logic Pro X. Now I have no "sound in-level" activity at all.

**Comment by pedrohqb** [comment]
I managed to have mic input with AppleALC through layout 66 but with a very bad sound output (speakers are great, but the headphone output, very bad).

Seems to be compromise: or we have bad audio, or we have mic input....

**Comment by pedrohqb** [comment]
My HDMI audio seems to be a problem because my monitor does not have audio output. I was planning to use an adaptor to have HDMI sound, but it seems not to be working. Maybe it is possible to circumvent that by forcing my monitor as a external display device? If so, how?

**Comment by asle** [comment]
> My HDMI audio seems to be a problem because my monitor does not have audio output. I was planning to use an adaptor to have HDMI sound, but it seems not to be working. Maybe it is possible to circumvent that by forcing my monitor as a external display device? If so, how?

I am using a DP to HDMI adapter since my monitor is HDMI. I have speakers in the monitor working. Not sure how you would define the external display as an audio device.

**Comment by pedrohqb** [comment]
Ok. I think I resolved the issue. The microphone input apparently doesn't work (it should no longer be supported by Apple). But if you use a headset that contains both audio and microphone on the same cable and insert it into the sound input, you will have the microphone working normally.
