### ISSUE TITLE
Issue with fan speed monitor

### ISSUE THREAD

**Issue by pedrohqb** [asle/lenovo_m93p_mini_hackintosh#4]
Hello. Even though your EFI folder contains SMCSuperIO.kext, I was unable to obtain any fan information.

Does that also happen to you?

**Comment by asle** [comment]
I have never been able to get any fan information on these mini-PCs (Lenovo, HP, Dell) even in Windows so this is not a hackintosh issue. I am able to get CPU temps and SSD span life.
