### ISSUE TITLE
The installer is damaged or incomplete message when installing Mojave

### ISSUE THREAD

**Issue by vaccinemedia** [asle/lenovo_m93p_mini_hackintosh#5]
I have created an installer USB using TonyMacX86 Unibeast (Mojave) and replaced it's EFI folder with yours after editing config.plist with serial number, UEFI etc.. It boots to the Mojave installer and I'm able to format the internal HD APFS no problem but on starting the installer I get the error "The installer is either damaged or incomplete".

The USB installer works with a different, clover-based EFI folder from here:
https://www.tonymacx86.com/threads/success-lenovo-m93p-m73p-tiny-mini-pc-i5-4570t-i7-4765t-yosemite-catalina.292082/

**Comment by asle** [comment]
Check your date on your hackintosh. From the installer window choose -> Terminal and type this:
date (enter). What do you get? Try to set the date back to 2018 or something. Use this command.
**date 0711141518** -> would set date to July 11, 2018 2:15
 Then try the installation again.

**Comment by vaccinemedia** [comment]
It turns out that it was a bad stick of RAM ;( I discovered this by trying to install Linux and that failed too with the message that the installation media is bad and researching into this led me to check the ram using memtest. I've not got one of the 4GB sticks that does work and one of the original 2GB sticks in and installed OK but no ethernet.
