### ISSUE TITLE
Big Sur Update

### ISSUE THREAD

**Issue by crottolo** [asle/lenovo_m93p_mini_hackintosh#6]
Hi, i have m93p with big sur but the efi folder isn't compatible with big sur.

Have you planned the update???
thanks

**Comment by asle** [comment]
Updated now to latest OpenCore 0.7.2. Did some changes, update SMBIOS etc. Have a look at the README and changes file. Works fine with Big Sur 11.3.1. Will try to upgrade to 11.5.1 but I am sure the current setup works fine. Remember to add in your own serials.

**Comment by asle** [comment]
Should work fine also with latest Big Sur 11.5.1.
