### ISSUE TITLE
can't shut down and sleep, it becomes a reboot

### ISSUE THREAD

**Issue by ccdos** [asle/lenovo_m93p_mini_hackintosh#7]
I have a problem that after installing bigsure 11.5.1, it can't shut down and sleep, it becomes a reboot. Everything else is fine. Please tell me how to check the problem?

**Comment by asle** [comment]
This sounds like a USB mapping problem. Have you used my SSDT files or created your own with **ssdttime**? Also the USB mapping kext is important. You can check in **IORegistryExplorer** what ports are active.
