### ISSUE TITLE
hello,multiboot problem

### ISSUE THREAD

**Issue by nj-dream** [asle/lenovo_m93p_mini_hackintosh#9]
Hello, I successfully installed 11.5.2 with your EFI, thank you very much for sharing.
I want to install another windows 10 on this hackintosh. Do you have any guides in this regard?

**Comment by asle** [comment]
I would always suggest windows on its own drive but this machine has no option for a second drive. You could try to install windows with Bootcamp but I never tried that in this machine. I think it is possible to install windows on a USB drive (preferably ssd) and OpenCore should see the windows drive.

**Comment by nj-dream** [comment]
谢谢指教，我来试试，如果成功，反馈到这里。😊

**Comment by nj-dream** [comment]
Thank you for your advice. I will try it. If it succeeds, I will report it here.

**Comment by nj-dream** [comment]
I have dual boot big sur and windows 10,guide in here: https://www.youtube.com/watch?v=6byZCRZ6XB8

**Comment by asle** [comment]
> I have dual boot big sur and windows 10,guide in here: https://www.youtube.com/watch?v=6byZCRZ6XB8

Very helpful video! Thanks!
